# Generated by Django 4.1 on 2022-08-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_delete_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('adress_id', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.TextField()),
                ('pais', models.TextField()),
                ('provincia', models.TextField()),
                ('calle', models.TextField()),
                ('numero', models.IntegerField()),
            ],
            options={
                'db_table': 'direccion',
                'managed': True,
            },
        ),
    ]