# Generated by Django 4.1 on 2022-08-29 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_direccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direccion',
            old_name='adress_id',
            new_name='address_id',
        ),
    ]