# Generated by Django 4.1 on 2022-08-29 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0004_rename_adress_id_direccion_address_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='numero',
        ),
    ]